
server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/suixing?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/suixing?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


  #    掐头去尾
  mvc: #静态资源配置
    view:
      prefix: /
      suffix: .html
      hiddenmethod:
        filter:
          enabled: true


  #模板引擎
  thymeleaf:
    prefix: classpath:static/
    suffix: .html
    cache: false

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    pool:
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
  cache:
    type: REDIS

